# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logdpoisbinom_cpp <- function(alpha) {
    .Call('_agents_logdpoisbinom_cpp', PACKAGE = 'agents', alpha)
}

logdbern_sum_cpp <- function(alpha, x) {
    .Call('_agents_logdbern_sum_cpp', PACKAGE = 'agents', alpha, x)
}

#' logsum using cpp 
#' @param lw log weights.
#' @export 
lw_logsum_cpp <- function(lw) {
    .Call('_agents_lw_logsum_cpp', PACKAGE = 'agents', lw)
}

#' normalize logweights
#' @param lw log weights.
#' @export 
lw_normalize_cpp <- function(lw) {
    .Call('_agents_lw_normalize_cpp', PACKAGE = 'agents', lw)
}

metropolis_condbern_cpp <- function(sum_x, alpha, num_mcmc) {
    .Call('_agents_metropolis_condbern_cpp', PACKAGE = 'agents', sum_x, alpha, num_mcmc)
}

rcppeigen_hello_world <- function() {
    .Call('_agents_rcppeigen_hello_world', PACKAGE = 'agents')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_agents_rcppeigen_outerproduct', PACKAGE = 'agents', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_agents_rcppeigen_innerproduct', PACKAGE = 'agents', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_agents_rcppeigen_bothproducts', PACKAGE = 'agents', x)
}

get_runifs <- function(n) {
    .Call('_agents_get_runifs', PACKAGE = 'agents', n)
}

idchecking_cpp <- function(sum_x, alpha, random_number) {
    .Call('_agents_idchecking_cpp', PACKAGE = 'agents', sum_x, alpha, random_number)
}

multinomial_resampling_cpp <- function(weights, ndraws, rand) {
    .Call('_agents_multinomial_resampling_cpp', PACKAGE = 'agents', weights, ndraws, rand)
}

multinomial_cpp <- function(logweights, uniform) {
    .Call('_agents_multinomial_cpp', PACKAGE = 'agents', logweights, uniform)
}

sir_bif_create_cpp <- function(y, nexts, nexti, logfbar, rho, N) {
    .Call('_agents_sir_bif_create_cpp', PACKAGE = 'agents', y, nexts, nexti, logfbar, rho, N)
}

sir_bif_update_cpp <- function(logpolicy, nexts, nexti, logfbar, lambda, gamma, rho, y, N, c) {
    invisible(.Call('_agents_sir_bif_update_cpp', PACKAGE = 'agents', logpolicy, nexts, nexti, logfbar, lambda, gamma, rho, y, N, c))
}

create_fbar_matrix <- function(lambda, gamma, N, c) {
    .Call('_agents_create_fbar_matrix', PACKAGE = 'agents', lambda, gamma, N, c)
}

update_fbar_matrix <- function(nexts, nexti, logfbar, lambda, gamma, N, c) {
    invisible(.Call('_agents_update_fbar_matrix', PACKAGE = 'agents', nexts, nexti, logfbar, lambda, gamma, N, c))
}

sir_csmc_update_f_matrix <- function(logf, xxprev, lambda_v, gamma_v, N) {
    invisible(.Call('_agents_sir_csmc_update_f_matrix', PACKAGE = 'agents', logf, xxprev, lambda_v, gamma_v, N))
}

smallpox_bif_create_cpp <- function(y, nexts, nexti, logfbar, rho, N) {
    .Call('_agents_smallpox_bif_create_cpp', PACKAGE = 'agents', y, nexts, nexti, logfbar, rho, N)
}

smallpox_bif_update_cpp <- function(logpolicy, nexts, nexti, logfbar, lambda, gamma, rho, y, N, c) {
    invisible(.Call('_agents_smallpox_bif_update_cpp', PACKAGE = 'agents', logpolicy, nexts, nexti, logfbar, lambda, gamma, rho, y, N, c))
}

sir_sample_x_given_si <- function(xx, lambda, gamma, scount, icount, N, P) {
    .Call('_agents_sir_sample_x_given_si', PACKAGE = 'agents', xx, lambda, gamma, scount, icount, N, P)
}

sis_get_alpha_full_cpp <- function(xx, lambda, gamma) {
    .Call('_agents_sis_get_alpha_full_cpp', PACKAGE = 'agents', xx, lambda, gamma)
}

sis_xx_gibbs_blocked_full_cpp <- function(xx, y, alpha0, lambda, gamma, rho, block_size, state_space) {
    invisible(.Call('_agents_sis_xx_gibbs_blocked_full_cpp', PACKAGE = 'agents', xx, y, alpha0, lambda, gamma, rho, block_size, state_space))
}

sis_xx_gibbs_singlesite_full_cpp <- function(xx, y, alpha0, lambda, gamma, rho) {
    invisible(.Call('_agents_sis_xx_gibbs_singlesite_full_cpp', PACKAGE = 'agents', xx, y, alpha0, lambda, gamma, rho))
}

sis_xx_gibbs_swap_full_cpp <- function(xx, alpha0, lambda, gamma) {
    invisible(.Call('_agents_sis_xx_gibbs_swap_full_cpp', PACKAGE = 'agents', xx, alpha0, lambda, gamma))
}

sis_forward_algorithm_cpp <- function(logf0, logdtransition, y, all_sum_x, rho) {
    .Call('_agents_sis_forward_algorithm_cpp', PACKAGE = 'agents', logf0, logdtransition, y, all_sum_x, rho)
}

sis_apf_exact_full_cpp <- function(y, alpha0, lambda, gamma, rho, num_particles, threshold, population_size) {
    .Call('_agents_sis_apf_exact_full_cpp', PACKAGE = 'agents', y, alpha0, lambda, gamma, rho, num_particles, threshold, population_size)
}

static_xx_gibbs_cpp <- function(xx_previous, alpha, rho, y) {
    .Call('_agents_static_xx_gibbs_cpp', PACKAGE = 'agents', xx_previous, alpha, rho, y)
}

